"""
Agent Hub - Markdown Catalog Generator

Generates a rich README.md and per-category markdown files from curated
enriched items. Output is deterministic: identical input always produces
identical output (timestamps are parameterized for test reproducibility).
"""

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.config import PROJECT_ROOT

logger = logging.getLogger(__name__)

# Map category enum values to output file paths (relative to project root)
CATEGORY_FILES = {
    "battle-tested": "docs/battle-tested.md",
    "new-upcoming": "docs/new-upcoming.md",
    "experimental": "docs/experimental.md",
}

# Human-readable category titles
CATEGORY_TITLES = {
    "battle-tested": "Battle-Tested",
    "new-upcoming": "New & Upcoming",
    "experimental": "Experimental",
}

# Category descriptions for the per-category files
CATEGORY_DESCRIPTIONS = {
    "battle-tested": (
        "Proven tools, frameworks, and techniques with significant adoption "
        "and a track record of real-world use in agentic AI coding workflows."
    ),
    "new-upcoming": (
        "Recently published tools and techniques that are gaining traction. "
        "These show promise but haven't yet achieved widespread adoption."
    ),
    "experimental": (
        "Prototype-stage research, alpha releases, and novel approaches. "
        "These are worth watching but may not be production-ready."
    ),
}


def sanitize_markdown(text: str, max_length: int = 150) -> str:
    """
    Sanitize text for use inside a markdown table cell.

    - Escapes pipe characters (|) which break table formatting
    - Strips newlines which break table rows
    - Truncates to max_length with ellipsis

    Args:
        text: Raw text to sanitize.
        max_length: Maximum characters before truncation.

    Returns:
        Sanitized string safe for markdown tables.
    """
    if not isinstance(text, str):
        return ""
    # Strip newlines and carriage returns
    text = text.replace("\n", " ").replace("\r", " ")
    # Escape pipe characters
    text = text.replace("|", "\\|")
    # Collapse multiple spaces
    text = " ".join(text.split())
    # Truncate
    if len(text) > max_length:
        text = text[: max_length - 3] + "..."
    return text


def generate_category_table(items: list[dict], category: str) -> str:
    """
    Generate a rich markdown table for items in a specific category.

    Items are sorted by relevance_score descending.

    Args:
        items: All curated items.
        category: Category to filter by (e.g., "battle-tested").

    Returns:
        Markdown table string.
    """
    filtered = [i for i in items if i.get("category") == category]
    filtered.sort(key=lambda x: x.get("relevance_score", 0), reverse=True)

    if not filtered:
        return "_No items yet in this category._\n"

    lines = [
        "| Title | Source | Relevance | Effectiveness | Tags | Summary |",
        "|-------|--------|-----------|---------------|------|---------|",
    ]

    for item in filtered:
        title = sanitize_markdown(item.get("title", "Untitled"), max_length=80)
        url = item.get("url", "#")
        source = item.get("source", "unknown")
        relevance = item.get("relevance_score", 0)
        effectiveness = item.get("effectiveness_score", 0)
        tags = ", ".join(item.get("enriched_tags", []))
        summary = sanitize_markdown(item.get("summary", ""), max_length=150)

        lines.append(
            f"| [{title}]({url}) | {source} | {relevance:.2f} | "
            f"{effectiveness:.2f} | {tags} | {summary} |"
        )

    return "\n".join(lines) + "\n"


def generate_category_file(
    items: list[dict],
    category: str,
    generated_at: Optional[str] = None,
) -> str:
    """
    Generate the full markdown file content for a single category.

    Args:
        items: All curated items.
        category: Category key (e.g., "battle-tested").
        generated_at: Optional timestamp string for reproducibility.

    Returns:
        Full markdown file content.
    """
    title = CATEGORY_TITLES.get(category, category.title())
    description = CATEGORY_DESCRIPTIONS.get(category, "")
    timestamp = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    table = generate_category_table(items, category)
    count = len([i for i in items if i.get("category") == category])

    return (
        f"# {title} Strategies\n"
        f"\n"
        f"> {description}\n"
        f"\n"
        f"**{count} items** in this category.\n"
        f"\n"
        f"{table}"
        f"\n"
        f"---\n"
        f"\n"
        f"_Auto-generated by Agent Hub on {timestamp}_\n"
    )


def generate_readme(
    items: list[dict],
    generated_at: Optional[str] = None,
) -> str:
    """
    Generate the root README.md catalog content.

    Includes project header, summary stats, top-10 per category,
    and links to full category files.

    Args:
        items: All curated items.
        generated_at: Optional timestamp string for reproducibility.

    Returns:
        Full README.md content.
    """
    timestamp = generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(items)

    # Count per category
    counts = {}
    for cat in CATEGORY_FILES:
        counts[cat] = len([i for i in items if i.get("category") == cat])

    # Build README
    sections = []

    # Header
    sections.append(
        "# 🤖 Agent Hub — Agentic AI Strategy Catalog\n"
        "\n"
        "A self-updating catalog of tools, techniques, and strategies for "
        "AI-powered coding agents (Claude Code, Cursor, Windsurf, Antigravity, "
        "GitHub Copilot, and more). Automatically scraped, enriched via LLM, "
        "and committed back to this repository.\n"
    )

    # Stats
    stats_lines = [
        f"\n## 📊 Overview\n",
        f"\n| Metric | Count |",
        f"|--------|-------|",
        f"| **Total curated items** | {total} |",
    ]
    for cat, count in counts.items():
        title = CATEGORY_TITLES.get(cat, cat)
        stats_lines.append(f"| {title} | {count} |")
    stats_lines.append("")
    sections.append("\n".join(stats_lines))

    # Per-category sections with top-10
    for cat, filepath in CATEGORY_FILES.items():
        title = CATEGORY_TITLES.get(cat, cat)
        cat_items = [i for i in items if i.get("category") == cat]
        cat_items.sort(key=lambda x: x.get("relevance_score", 0), reverse=True)
        top_items = cat_items[:10]

        section = f"\n## {title}\n\n"

        if top_items:
            table = generate_category_table(top_items, cat)
            section += table
        else:
            section += "_No items yet._\n"

        section += f"\n👉 [View all {title} strategies]({filepath})\n"
        sections.append(section)

    # Footer
    sections.append(
        f"\n---\n"
        f"\n"
        f"_Auto-generated by Agent Hub on {timestamp}. "
        f"Data sourced from GitHub, Reddit, and technical blogs._\n"
    )

    return "\n".join(sections)


def write_catalog(
    items: list[dict],
    output_dir: Optional[Path] = None,
    generated_at: Optional[str] = None,
) -> dict:
    """
    Write the full catalog: README.md + per-category markdown files.

    Args:
        items: Curated enriched items.
        output_dir: Root directory for output. Defaults to PROJECT_ROOT.
        generated_at: Optional timestamp for reproducibility.

    Returns:
        Stats dict: {"readme_written": True, "category_files": 3, "total_items": N}
    """
    root = output_dir or PROJECT_ROOT

    # Ensure docs/ directory exists
    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    # Write README.md
    readme_content = generate_readme(items, generated_at=generated_at)
    readme_path = root / "README.md"
    readme_path.write_text(readme_content, encoding="utf-8")
    logger.info(f"Wrote {readme_path}")

    # Write per-category files
    category_count = 0
    for cat, rel_path in CATEGORY_FILES.items():
        content = generate_category_file(items, cat, generated_at=generated_at)
        file_path = root / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        logger.info(f"Wrote {file_path}")
        category_count += 1

    stats = {
        "readme_written": True,
        "category_files": category_count,
        "total_items": len(items),
    }
    logger.info(f"Catalog generated: {stats}")
    return stats
